### ISSUE TITLE
Request for grade

### ISSUE THREAD

**Issue by JiffyBees** [JiffyBees/animal-rescue-website#2]
Its really not a good website there are a number of issues but I did it.
@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
